---
name: Run PyTest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.12"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          pip install tox
          tox -e py${{matrix.python-version}}

      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: "pytest-${{ matrix.python-version }}.xml"
          path: junit/test-results.xml
          if-no-files-found: error
